[2025-04-06T07:57:20.993+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_file_upload_dag.run_data_loading manual__2025-04-06T07:57:20.225142+00:00 [queued]>
[2025-04-06T07:57:21.001+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_file_upload_dag.run_data_loading manual__2025-04-06T07:57:20.225142+00:00 [queued]>
[2025-04-06T07:57:21.002+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-06T07:57:21.020+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_data_loading> on 2025-04-06 07:57:20.225142+00:00
[2025-04-06T07:57:21.024+0000] {standard_task_runner.py:60} INFO - Started process 201 to run task
[2025-04-06T07:57:21.027+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gcs_file_upload_dag', 'run_data_loading', 'manual__2025-04-06T07:57:20.225142+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/gcs_fileupload_dag.py', '--cfg-path', '/tmp/tmp35ii7cm2']
[2025-04-06T07:57:21.029+0000] {standard_task_runner.py:88} INFO - Job 202: Subtask run_data_loading
[2025-04-06T07:57:21.043+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-06T07:57:21.076+0000] {task_command.py:423} INFO - Running <TaskInstance: gcs_file_upload_dag.run_data_loading manual__2025-04-06T07:57:20.225142+00:00 [running]> on host 5638537b560c
[2025-04-06T07:57:21.148+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_file_upload_dag' AIRFLOW_CTX_TASK_ID='run_data_loading' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T07:57:20.225142+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T07:57:20.225142+00:00'
[2025-04-06T07:57:21.149+0000] {gcs_fileupload_dag.py:16} INFO - Calling data_loading from DAG...
[2025-04-06T07:57:21.150+0000] {logging_mixin.py:188} INFO - Starting data_loading...
[2025-04-06T07:57:21.463+0000] {logging_mixin.py:188} INFO - GitHub API rate limit: 5000/5000
[2025-04-06T07:57:21.465+0000] {logging_mixin.py:188} INFO - Error searching repositories: created
[2025-04-06T07:57:21.468+0000] {gcs_fileupload_dag.py:18} INFO - Done running data_loading.
[2025-04-06T07:57:21.470+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-06T07:57:21.489+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gcs_file_upload_dag, task_id=run_data_loading, execution_date=20250406T075720, start_date=20250406T075720, end_date=20250406T075721
[2025-04-06T07:57:21.520+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-06T07:57:21.539+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
