[2025-04-06T07:55:08.119+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_file_upload_dag.run_data_loading scheduled__2025-04-06T07:40:00+00:00 [queued]>
[2025-04-06T07:55:08.131+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_file_upload_dag.run_data_loading scheduled__2025-04-06T07:40:00+00:00 [queued]>
[2025-04-06T07:55:08.132+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-06T07:55:08.152+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_data_loading> on 2025-04-06 07:40:00+00:00
[2025-04-06T07:55:08.159+0000] {standard_task_runner.py:60} INFO - Started process 177 to run task
[2025-04-06T07:55:08.164+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gcs_file_upload_dag', 'run_data_loading', 'scheduled__2025-04-06T07:40:00+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/gcs_fileupload_dag.py', '--cfg-path', '/tmp/tmpeyp08imm']
[2025-04-06T07:55:08.167+0000] {standard_task_runner.py:88} INFO - Job 200: Subtask run_data_loading
[2025-04-06T07:55:08.191+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-06T07:55:08.243+0000] {task_command.py:423} INFO - Running <TaskInstance: gcs_file_upload_dag.run_data_loading scheduled__2025-04-06T07:40:00+00:00 [running]> on host 5638537b560c
[2025-04-06T07:55:08.406+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_file_upload_dag' AIRFLOW_CTX_TASK_ID='run_data_loading' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T07:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-06T07:40:00+00:00'
[2025-04-06T07:55:08.409+0000] {gcs_fileupload_dag.py:16} INFO - Calling data_loading from DAG...
[2025-04-06T07:55:08.410+0000] {logging_mixin.py:188} INFO - Starting data_loading...
[2025-04-06T07:55:08.716+0000] {logging_mixin.py:188} INFO - GitHub API rate limit: 5000/5000
[2025-04-06T07:55:08.717+0000] {logging_mixin.py:188} INFO - Error searching repositories: created
[2025-04-06T07:55:08.719+0000] {gcs_fileupload_dag.py:18} INFO - Done running data_loading.
[2025-04-06T07:55:08.720+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-06T07:55:08.734+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gcs_file_upload_dag, task_id=run_data_loading, execution_date=20250406T074000, start_date=20250406T075508, end_date=20250406T075508
[2025-04-06T07:55:08.779+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-06T07:55:08.799+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
